name: ${plugin_name}
version: ${plugin_vers}
main: xyz.webmc.${plugin_iden}.bukkit.${plugin_name}Bukkit
description: ${plugin_desc}
website: ${plugin_site}
authors: [${plugin_athr}]
contributors: [${plugin_ctbr}]
depend: [${plugin_depa}]
provides: [${plugin_prov}]
softdepend: [${plugin_sdpa}]
commands:
  originblacklist: